name: 'Arweave archive action'
description: 'Archive page html and screenshot of url'
author: 'pawanpaudel93'
inputs:
  jwk:
    description: 'Arweave wallet JWK'
    required: true
  url_file_path:
    description: 'File containing urls lines to capture'
    required: true
  gateway_url:
    description: 'URL of the service used to access network data'
    required: false
    default: 'https://arweave.net'
  bundler_url:
    description: 'URL of the service used to submit data to the network when possible instead of using the gateway'
    required: false
    default: 'https://node2.bundlr.network'
  output_file_path:
    description: 'JSON file to save the results'
    required: false
    default: 'saved.json'
runs:
  using: 'node16'
  main: 'dist/index.js'
