name: arweave-archive-action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      - name: Archive webpage and screenshot
        uses: ./
        with:
          jwk: ${{ secrets.JWK }}
          url_file_path: 'urls.txt'
          gateway_url: 'https://ar-io.net'
